In [1]:
import pandas as pd
import numpy as np

In [2]:
housing=pd.read_csv('train.csv')
housing.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
lables = housing[['SalePrice']]
features =housing.drop(['SalePrice'], axis=1)

In [5]:
features.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC Fence MiscFeature  \
0         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
1         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
2         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
3         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   
4         Lvl    AllPub  ...           0        0    NaN   NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      2    2008        WD         Normal  
1       0      5    2007        WD         Normal  
2       0      9    2008        WD         Normal  
3       0      2    2006        WD        Abnorml  
4       0     12    2008        WD         Normal  

[5 rows x 80 columns]

In [6]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [7]:
lables.head()

SalePrice
0     208500
1     181500
2     223500
3     140000
4     250000

In [14]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(features, lables, test_size=0.2,random_state=42)


In [19]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

# Pipeline for numeric attributes
numeric_pipeline = Pipeline([
    ('median_imputer', SimpleImputer(strategy='median')),
    ('std_scaler', StandardScaler())
])

# Pipline for categorical attributes
categorical_pipeline = Pipeline([
    ('one_hot_encoder',OneHotEncoder())
])

In [29]:
from sklearn import set_config

set_config(display='diagram')

numeric_pipeline


TypeError: set_config() got an unexpected keyword argument 'display'

In [47]:
from sklearn.compose import ColumnTransformer

numeric_attributes = [
    'Id','MSSubClass','OverallQual','OverallCond','YearBuilt','TotalBsmtSF','LowQualFinSF','GrLivArea','Fireplaces','GarageCars','GarageArea','WoodDeckSF','OpenPorchSF','ScreenPorch','PoolArea','LotArea','MoSold','YrSold',
    
]

pipeline = ColumnTransformer([
    ('numerical_transformers', numeric_pipeline, numeric_attributes),
    ('categorical_transformers', categorical_pipeline, ['Neighborhood']),
])

In [48]:
pipeline

ColumnTransformer(n_jobs=None, remainder='drop', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('numerical_transformers',
                                 Pipeline(memory=None,
                                          steps=[('median_imputer',
                                                  SimpleImputer(add_indicator=False,
                                                                copy=True,
                                                                fill_value=None,
                                                                missing_values=nan,
                                                                strategy='median',
                                                                verbose=0)),
                                                 ('std_scaler',
                                                  StandardScaler(copy=True,
                                                                 with_mean=Tru

In [49]:
pipeline.fit_transform(x_train)[0]

array([-1.11928402, -0.8667643 , -0.82044456,  0.3722173 , -0.45546896,
        0.57261219, -0.11899866, -0.40709315, -0.95859215, -1.05654384,
       -0.86383727,  1.18840233, -0.71435182, -0.27583782, -0.07099284,
       -0.21289571, -0.13341669,  1.65006527,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ])

array([-1.1192840216867437, -0.8667643047469886, -0.8204445578548297,
       0.37221730085603477, -0.4554689634533773, 0.5726121928947197,
       -0.11899866377895676, -0.40709314807972335, -0.9585921495629545,
       -1.056543843657237, -0.8638372713165864, 1.1884023292892827,
       -0.7143518217141828, -0.2758378238577077, -0.07099283776824153,
       -0.21289571021689285, -0.1334166899817642, 1.6500652739221804, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'RL', 70.0,
       'Pave', nan, 'Reg', 'Lvl', 'AllPub', 'Inside', 'Gtl', 'Norm',
       'Norm', '1Fam', '1Story', 1957, 'Gable', 'CompShg', 'MetalSd',
       'MetalSd', 'None', 0.0, 'TA', 'Gd', 'CBlock', 'TA', 'TA', 'No',
       'Rec', 922, 'Unf', 0, 392, 'GasA', 'TA', 'Y', 'SBrkr', 1314, 0, 1,
       0, 1, 0, 3, 1, 'TA', 5, 'Typ', nan, 'Attchd', 1957.0, 'RFn', 'TA',
       'TA', 'Y', 0, 0, nan, nan, nan, 0, 'WD', 'Normal'], dtype=object

In [50]:
from sklearn.linear_model import LinearRegression

model_pipline = Pipeline([
    ('preprocessing', pipeline),
    ('model', LinearRegression())
    
])

model_pipline

Pipeline(memory=None,
         steps=[('preprocessing',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('numerical_transformers',
                                                  Pipeline(memory=None,
                                                           steps=[('median_imputer',
                                                                   SimpleImputer(add_indicator=False,
                                                                                 copy=True,
                                                                                 fill_value=None,
                                                                                 missing_values=nan,
                                                                                 strategy='median',
                                  

In [51]:
model_pipline.fit(x_train, y_train)


Pipeline(memory=None,
         steps=[('preprocessing',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('numerical_transformers',
                                                  Pipeline(memory=None,
                                                           steps=[('median_imputer',
                                                                   SimpleImputer(add_indicator=False,
                                                                                 copy=True,
                                                                                 fill_value=None,
                                                                                 missing_values=nan,
                                                                                 strategy='median',
                                  

In [52]:
model_pipline.predict(x_test)

array([[156599.09535474],
       [326900.14354589],
       [122925.06913566],
       [189751.16850766],
       [271819.75384879],
       [ 55652.33135245],
       [250930.4264786 ],
       [144496.62937448],
       [ 48397.48121179],
       [153183.63819444],
       [161145.02916239],
       [113140.30466762],
       [ 90318.78709414],
       [266405.53479366],
       [184005.79245694],
       [121498.06057809],
       [203083.58709731],
       [130244.30874702],
       [116932.59699253],
       [209885.85017822],
       [166111.08891125],
       [226458.00410754],
       [181846.31214126],
       [126149.77995263],
       [199600.50128797],
       [145425.12299075],
       [191937.71579952],
       [102057.2219096 ],
       [179482.20221571],
       [201583.05300423],
       [132717.07588992],
       [301130.01898139],
       [233000.161624  ],
       [106987.60650016],
       [264492.43640841],
       [158210.00501435],
       [138540.17393696],
       [220654.79348572],
       [3364

In [57]:
from sklearn.metrics import mean_squared_error, r2_score

predictions = model_pipline.predict(x_test)
rmse = mean_squared_error(y_test, predictions, squared=False)
r2 = r2_score(y_test, predictions)
print(f'RMSE: {rmse}')
print(f'R-squared: {r2}')

RMSE: 34270.5306591398
R-squared: 0.846881444160933
